apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: amanmemilih-frontend-project
  namespace: argocd
spec:
  description: Amanmemilih Frontend Project
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://aks-dev-yazid-resource-group-eajtsi8n.hcp.southeastasia.azmk8s.io:443
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: false
  roles:
    - name: admin
      description: Role for AmanMemilih Project
      policies:
        - p, proj:amanmemilih-frontend-project:admin, applications, *, amanmemilih-frontend-project/*, allow
      groups:
        - general
