apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: api-eventeens-project
  namespace: argocd
spec:
  description: Api Eventeens Project
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://10.21.64.1:6443
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: false
  roles:
    - name: admin
      description: Role for Api Eventeens Project for Tugas MEKPL
      policies:
        - p, proj:api-eventeens-project:admin, applications, *, api-eventeens-project/*, allow
      groups:
        - general
