apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: motionlab-project
  namespace: argo
spec:
  description: Api Eventeens Project
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: false
  roles:
    - name: admin
      description: Role for Motionlab Project
      policies:
        - p, proj:motionlab-project:admin, applications, *, motionlab-project/*, allow
      groups:
        - general
