apiVersion: batch/v1
kind: Job
metadata:
  generateName: {{ .Release.Name }}-zap-dast-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: zap
          image: ghcr.io/zaproxy/zaproxy:stable
          args:
            - sh
            - -c
            - |
              echo "Waiting for NodePort to be ready..."
              until curl -sf {{ .Values.dast.targetUrl }}; do
                sleep 5
              done
              zap-baseline.py \
                -t {{ .Values.dast.targetUrl }} \
                -r report.html \
                -m 0
