apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frontend-secrets
  namespace: amanmemilih-fe
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azurekv-store
    kind: SecretStore
  target:
    name: frontend-secrets
    creationPolicy: Owner
  data:
    - secretKey: VITE_API_URL
      remoteRef:
        key: vite-api-url
