apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azurekv-store
  namespace: amanmemilih-fe
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-dev-rg-yazid-poc.vault.azure.net/"
      serviceAccountRef:
        name: kv-reader-sa
