apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amanmemilih
  namespace: argocd
spec:
  project: amanmemilih-project
  source:
    repoURL: https://github.com/yazidalg/motion-chart.git
    path: .
    targetRevision: main
    helm:
      valueFiles:
        - "amanmemilih/values.yaml"
  destination:
    server: https://10.21.64.1:6443
    namespace: amanmemilih-be
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
